services:
  java-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-application
    ports:
      - 8080:8080
    restart: always
    networks:
      - default
    depends_on:
      - mysql-db
    env_file:
      - .env

  mysql-db:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: mysql-db
    ports:
      - 3309:3306
    restart: always
    networks:
      - default
    volumes:
      - shared-data:/var/lib/mysql
    env_file:
      - .env

#  k6:
#    build:
#      context: k6
#      dockerfile: Dockerfile
#    container_name: k6
#    restart: always
#    networks:
#      - default
#    depends_on:
#      - java-application
#    env_file:
#      - .env

networks:
  default:
    driver: bridge

volumes:
  shared-data: